# Generated by Django 5.2.4 on 2025-08-04 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceSettings', '0002_leavetype_attendancetype_is_lop_leaverequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendenceSettings.attendancetype'),
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='leave_type',
        ),
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'ordering': ['-year', 'leave_type__title']},
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='attendance_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='attendenceSettings.attendancetype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
    ]
