# Generated by Django 5.2.4 on 2025-08-04 08:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceSettings', '0004_status_remove_leaverequest_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='attendancepunch',
            name='action',
        ),
        migrations.RemoveField(
            model_name='attendancepunch',
            name='attendance',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='is_manual',
            new_name='is_late',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attendancetype',
            name='is_lop',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='half_day_type',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_half_day',
        ),
        migrations.AddField(
            model_name='attendance',
            name='action_type',
            field=models.CharField(blank=True, choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('break_start', 'Break Start'), ('break_end', 'Break End'), ('lunch_start', 'Lunch Start'), ('lunch_end', 'Lunch End'), ('half_day', 'Half Day'), ('wfh', 'Work From Home')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='company',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancetype',
            name='company',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='company',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='overtime_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='attendenceSettings.source'),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='AttendancePunch',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_time',
        ),
    ]
