# Generated by Django 5.2.4 on 2025-08-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceSettings', '0005_source_remove_attendancepunch_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date_check_in']},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='date_check_in',
        ),
        migrations.RenameField(
            model_name='attendancetype',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='leavebalance',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='working_hour',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
