# Generated by Django 5.2.4 on 2025-08-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceSettings', '0006_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetype',
            name='is_leave',
            field=models.BooleanField(default=False),
        ),
    ]
