# Generated by Django 5.2.4 on 2025-08-05 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceSettings', '0007_attendancetype_is_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='approved_at',
            new_name='action_at',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='approved_by',
            new_name='action_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='action_type',
        ),
        migrations.AddField(
            model_name='attendance',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='attendenceSettings.action'),
        ),
        migrations.CreateModel(
            name='LeaveBalanceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.IntegerField(blank=True, null=True)),
                ('company', models.IntegerField(blank=True, null=True)),
                ('allocated_days', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('used_days', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('remaining_days', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('carried_forward_days', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='attendenceSettings.attendancetype')),
            ],
            options={
                'ordering': ['-year', 'leave_type__title'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
