# Generated by Django 5.2.1 on 2025-08-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendenceSettings', '0008_action_rename_approved_at_leaverequest_action_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(blank=True, null=True)),
                ('financial_year', models.PositiveIntegerField(default=2024, help_text='Financial year (e.g., 2024)')),
                ('annual_leave_days', models.PositiveIntegerField(default=21, help_text='Annual leave days')),
                ('sick_leave_days', models.PositiveIntegerField(default=14, help_text='Sick leave days')),
                ('casual_leave_days', models.PositiveIntegerField(default=7, help_text='Casual leave days')),
                ('maternity_leave_days', models.PositiveIntegerField(default=180, help_text='Maternity leave days')),
                ('paternity_leave_days', models.PositiveIntegerField(default=15, help_text='Paternity leave days')),
                ('allow_carry_forward', models.BooleanField(default=True, help_text='Allow carry forward')),
                ('require_approval', models.BooleanField(default=True, help_text='Require approval')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company', '-financial_year', '-created_at'],
                'unique_together': {('company', 'financial_year')},
            },
        ),
        migrations.DeleteModel(
            name='LeaveBalanceMapping',
        ),
    ]
