# Generated by Django 5.2.4 on 2025-08-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftSetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_head',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='subshift',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.DeleteModel(
            name='ShiftHeadType',
        ),
    ]
